### ISSUE TITLE
how to use my own key for encryption ?

### ISSUE THREAD

**Issue by mridah** [sveinungkb/encrypted-userprefs#8]
I cannot figure out where you have mentioned the encryption key in the code. Can you please tell me how to use my own key for encryption ? @sveinungkb

**Comment by ninbit** [comment]
Just change "SometopSecretKey1235" in
`SecurePreferences preferences = new SecurePreferences(context, "my-preferences", "SometopSecretKey1235", true);`

**Comment by sveinungkb** [comment]
Thanks @ninbit, that is correct. Hope that helps @mridah.

**Comment by mridah** [comment]
Thanks @ninbit and @sveinungkb
