### ISSUE TITLE
Generating key at runtim e.g. with timestamp

### ISSUE THREAD

**Issue by ninbit** [sveinungkb/encrypted-userprefs#9]
Generating the key at runtime for example with time stamp cause any error? Because the key will change every time the code runs

**Comment by sveinungkb** [comment]
Yes, you cannot change the key after instantiating this class instance.

**Comment by ninbit** [comment]
I didn't mean to change it. The aim for generating the key at runtime is hiding the key from anyone who decompiles my app.
